export const styles = {
    pageFrame: "h-full mx-auto p-0 flex flex-col max-w-[500px] font-[Roboto] text-mtw-gray-500 dark:text-mtw-gray-400 small:border-2 small:border-mtw-gray-350 dark:border-mtw-gray-500",
    title: "text-md mb-2 text-gray-600 text-2xl dark:text-gray-300 font-bold",
    subTitle: "font-bold text-md mb-4 text-gray-400",
    subTitleModal: "font-bold text-md text-gray-600",
    label: "text-gray-600 dark:text-gray-300",
    labelB: "text-gray-600 dark:text-gray-light-1 font-bold",
    comments: "text-xs text-gray-400 dark:text-gray-300",
    link: "text-blue-400 hover:text-blue-600 font-bold font-base cursor-pointer",
    linkM: "text-blue-400 hover:text-blue-300 font-bold font-base cursor-pointer",
    linkMA: "text-white font-bold font-base cursor-pointer",
    textInput: "px-2 py-1 border border-gray-300 focus:border-gray-300 focus:dark:border-gray-300 active:border-gray-300 active:dark:border-gray-300 rounded-md w-full dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300",
    textDisabled: "relative border border-gray-300 rounded p-2 pr-2 cursor-pointer",
    button: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1.5 px-4 rounded-md max-w-[200px] border-blue-500 border",
    buttonS: "bg-white hover:bg-blue-50 text-blue-500 font-bold py-1.5 px-4 rounded-md max-w-[200px] border-blue-500 border",
    smButton: "bg-white text-gray-400 hover:text-gray-500 text-sm py-1 px-1 cursor-pointer rounded-md",
    smButtonA: "bg-gray-300 text-gray-600 hover:text-gray-700 text-sm py-1 px-1 cursor-pointer rounded-md",
    select: "w-full appearance-none border border-gray-300 outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-600 py-2 rounded focus:border-gray-300 focus:dark:border-gray-300 active:border-gray-300 active:dark:border-gray-300",
}