export const styles = {
    pageFrame: "h-full mx-auto p-0 flex flex-col max-w-[500px] font-[Roboto] text-mtw-gray-500 dark:text-mtw-gray-400 small:border-2 small:border-mtw-gray-350 dark:border-mtw-gray-500",
    title: "text-md mb-2 text-gray-600 text-2xl dark:text-gray-300 font-bold",
    subTitle: "font-bold text-md mb-4 text-gray-400",
    subTitleModal: "font-bold text-md text-gray-600",
    label: "text-gray-600 dark:text-gray-300",
    labelB: "text-gray-600 dark:text-gray-light-1 font-bold",
    comments: "text-xs text-gray-400 dark:text-gray-300",
    link: "text-blue-400 hover:text-blue-600 font-bold font-base cursor-pointer",
    textInput: "px-2 py-1 border border-gray-300 focus:border-gray-300 focus:dark:border-gray-300 active:border-gray-300 active:dark:border-gray-300 rounded-md w-full dark:bg-gray-700 dark:border-gray-600 dark:text-gray-300",
    textDisabled: "relative border border-gray-300 rounded p-2 pr-2 cursor-pointer",
    button: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-1.5 px-4 rounded-md max-w-[200px] border-blue-500 border",
    buttonS: "bg-white hover:bg-blue-50 text-blue-500 font-bold py-1.5 px-4 rounded-md max-w-[200px] border-blue-500 border",
    smButton: "bg-white text-gray-400 hover:text-gray-500 text-sm py-1 px-1 cursor-pointer rounded-md",
    smButtonA: "bg-gray-300 text-gray-600 hover:text-gray-700 text-sm py-1 px-1 cursor-pointer rounded-md",
    select: "w-full appearance-none border border-gray-300 outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-600 py-2 rounded focus:border-gray-300 focus:dark:border-gray-300 active:border-gray-300 active:dark:border-gray-300",
}

export const mStyles = {
    footer: "w-full mx-auto max-w-screen bg-blue-light-5 py-0 h-auto",
    label: "text-gray-light-2 mt-0 dark:text-gray-light-1",
    labelB: "text-gray-light-2 mt-0 dark:text-gray-light-1 font-bold",
    title: "flex justify-center my-4 text-blue-dark-1 text-xl xxxs:text-2xl xxs:text-3xl dark:text-white font-bold",
    subTitle: "text-g-5 dark:text-white font-bold mb-1 mt-4 relative w-fit",
    subTitleU: "text-g-5 dark:text-white font-bold mb-1 mt-4 relative w-full border-b border-blue-light-4",
    subTitleView: "text-g-5 dark:text-white font-bold mb-1 relative w-fit",
    subTitleModal: "text-md text-white",
    subTitleBlue: "text-blue-light-5 mb-1 relative w-fit text-lg",
    textInput: "border border-blue-light-4 focus:border-blue-light-4 focus:dark:border-blue-light-5 active:border-blue-light-4 active:dark:border-blue-light-5 rounded-md w-full dark:bg-blue-dark-4 dark:border-b-5 dark:text-white",
    likeInput: "border border-blue-light-4 rounded-md px-2 py-1.5 w-full bg-white dark:bg-blue-dark-4 dark:border-b-5 dark:text-white",
    likeInputD: "border border-blue-light-4 rounded-md px-2 py-1.5 w-full bg-blue-light-2 dark:bg-blue-dark-4 dark:border-b-5 dark:text-white",
    textDisabled: "relative border border-blue-light-4 rounded p-2 pr-2 text-g-5 dark:text-white",
    buttonC: "border border-blue-light-4 text-blue-light-5 font-bold py-2.5 px-4 rounded-md",
    button: "bg-blue-light-5 text-white font-bold py-2.5 px-4 rounded-md",
    buttonA: "bg-blue-light-5 text-white font-bold py-1.5 px-4 rounded-md",
    buttonG1: "text-xs border border-gray-light-1 text-gray-light-3 dark:text-gray-light-1 dark:border-gray-light-2 font-bold py-0.5 px-4 rounded-md",
    buttonG2: "text-xs bg-gray-light-1 border border-gray-light-1 text-gray-light-3 dark:text-gray-dark-3 font-bold py-0.5 px-4 rounded-md",
    buttonS1: "text-xs border border-blue-light-4 text-blue-light-5 font-bold py-0.5 px-4 rounded-md",
    buttonS2: "text-xs bg-blue-light-5 border border-blue-light-5 text-white font-bold py-0.5 px-4 rounded-md",
    buttonSM1: "text-[10px] border border-blue-light-4 text-blue-light-5 font-bold py-0 px-2 rounded-md",
    buttonSM2: "text-[10px] bg-blue-light-5 border border-blue-light-5 text-white font-bold py-0 px-2 rounded-md",
    buttonS: "text-xs text-white font-bold py-0.5 px-4 rounded-md",
    mnemonic: " bg-white dark:bg-gray-dark-3 text-gray-dark-3 dark:text-white rounded p-4 border border-blue-light-4 text-center font-bold overflow-auto break-words text-lg",
    link: "text-blue-light-5 dark:text-blue-light-4 font-bold font-base cursor-pointer",
    linkD: " dark:text-blue-dark-1 text-blue-light-3 font-bold font-base cursor-pointer underline underline-offset-4 pb-1",
    text: "text-gray-dark-3 dark:text-gray-dark-2",
    comments: "text-sm text-gray-dark-3 dark:text-gray-dark-2",
    select: "w-full appearance-none border-none outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-light-4 py-2 rounded-md focus:border-none focus:dark:border-none active:border-none active:dark:border-none text-center items-center tablet:text-left tablet:items-left bg-white truncate dark:bg-gray-light-4 dark:text-white",
    selectB: "w-full focus:ring-0 cursor-pointer border border-blue-light-4 focus:border-blue-light-4 focus:dark:border-blue-light-5 active:border-blue-light-4 active:dark:border-blue-light-5 text-gray-light-4 py-1.5 rounded-md  text-center items-center tablet:text-left tablet:items-left bg-white truncate dark:bg-gray-light-4 dark:text-white",
    selectLeft: "w-full appearance-none border-none outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-light-4 py-2 rounded-lg focus:border-none focus:dark:border-none active:border-none active:dark:border-none text-left items-left bg-white truncate dark:bg-gray-light-4 dark:text-white border-blue-light-5",
    selectTop: "w-full appearance-none outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-light-4 py-1 rounded-lg text-left items-left bg-white truncate dark:bg-gray-light-4 dark:text-white border-blue-light-5",
    selectView: "font-bold text-g-5 dark:text-white bg-transparent appearance-none border-none outline-none focus:ring-0 cursor-pointer focus:outline-none text-gray-light-4 rounded-lg focus:border-none focus:dark:border-none active:border-none active:dark:border-none text-left items-left truncate dark:bg-gray-light-4 dark:text-white",
    spin: "animate-spin h-8 w-8 rounded-full border-4 border-t-blue-light-5 border-r-blue-light-5 border-b-blue-light-2 border-t-l-blue-light-2",
    radio: "relative float-left mr-1 mt-0.5 h-5 w-5 appearance-none rounded-full border-2 border-solid border-neutral-300 before:pointer-events-none before:absolute before:h-4 before:w-4 before:scale-0 before:rounded-full before:bg-transparent before:opacity-0 before:shadow-[0px_0px_0px_3px_transparent] before:content-[''] after:absolute after:z-[1] after:block after:h-4 after:w-4 after:rounded-full after:content-[''] checked:m-border-primary checked:before:opacity-[0.16] checked:after:absolute checked:after:left-1/2 checked:after:top-1/2 checked:after:h-[0.625rem] checked:after:w-[0.625rem] checked:after:rounded-full checked:after:m-border-primary checked:after:bg-primary checked:after:content-[''] checked:after:[transform:translate(-50%,-50%)] hover:cursor-pointer hover:before:opacity-[0.04] hover:before:shadow-[0px_0px_0px_3px_rgba(0,0,0,0.6)] focus:shadow-none focus:outline-none focus:ring-0 focus:before:scale-100 focus:before:opacity-[0.12] focus:before:shadow-[0px_0px_0px_3px_rgba(0,0,0,0.6)] focus:before:transition-[box-shadow_0.2s,transform_0.2s] checked:focus:m-border-primary checked:focus:before:scale-100 checked:focus:before:shadow-[0px_0px_0px_3px_#3b71ca] checked:focus:before:transition-[box-shadow_0.2s,transform_0.2s] dark:border-neutral-600 dark:checked:m-border-primary dark:checked:after:m-border-primary dark:checked:after:bg-primary dark:focus:before:shadow-[0px_0px_0px_3px_rgba(255,255,255,0.4)] dark:checked:focus:m-border-primary dark:checked:focus:before:shadow-[0px_0px_0px_3px_#3b71ca] type-radio dark:bg-transparent"
} 